export const ADD_POSTIT = 'ADD_POSTIT';
export const REMOVE_POSTIT = 'REMOVE_POSTIT';
export const DISPLAY_ADD_POSTIT_BUTTON = 'DISPLAY_ADD_POSTIT_BUTTON';
export const DISPLAY_ADD_POSTIT_FORM = 'DISPLAY_ADD_POSTIT_FORM';
